# Generated by Django 3.0.6 on 2020-05-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('nickname', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('ig', models.CharField(max_length=100, null=True)),
                ('fb', models.CharField(max_length=100, null=True)),
                ('photo_whole', models.CharField(max_length=150)),
                ('photo_half', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
