# Generated by Django 3.0.6 on 2020-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
