# Generated by Django 3.0.6 on 2020-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_players_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='photo_half',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo_whole',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
